version: "3.4"
services:
  nginx:
    image: nginx:latest
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    volumes:
      - "/root/PROD/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"

  drive-ui:
    image: "drivehub.azurecr.io/meateam/drive-ui:v2.0.1"
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  api-gateway:
    image: "drivehub.azurecr.io/meateam/api-gateway:curl"
    env_file:
      - /root/PROD/kd.config
    healthcheck:
      test: curl -f http://localhost:8080/api/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3001:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
    depends_on:
      - upload-service
      - download-service
      - file-service
      - authentication-service
      - permission-service
      - search-service
      - gotenberg

  upload-service:
    image: "drivehub.azurecr.io/meateam/upload-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - /root/PROD/kd.config
    ports:
      - "3002:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  download-service:
    image: "drivehub.azurecr.io/meateam/download-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - /root/PROD/kd.config
    ports:
      - "3003:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  file-service:
    image: "drivehub.azurecr.io/meateam/file-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - /root/PROD/kd.config
    ports:
      - "3004:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  authentication-service:
    image: "drivehub.azurecr.io/meateam/authentication-service:curl"
    ports:
      - "3005:8080"
    env_file:
      - /root/PROD/kd.config
    healthcheck:
      test: curl -f http://localhost:8080/auth/healthcheck || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - user-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  user-service:
    image: "drivehub.azurecr.io/meateam/user-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3007:8080"
    env_file:
      - /root/PROD/kd.config
    depends_on:
      - redis
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  permission-service:
    image: "drivehub.azurecr.io/meateam/permission-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3008:8080"
    env_file:
      - /root/PROD/kd.config
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  search-service:
    image: "drivehub.azurecr.io/meateam/search-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - /root/PROD/kd.config
    ports:
      - "3009:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  gotenberg:
    image: "drivehub.azurecr.io/meateam/gotenberg:6"
    env_file:
      - /root/PROD/kd.config
    tmpfs:
      - /tmp
      - /gotenberg/tmp
    ports:
      - "3010:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  spike-service:
    image: "drivehub.azurecr.io/meateam/spike-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - /root/PROD/kd.config
    depends_on:
      - redis
    ports:
      - "3011:8080"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  delegation-service:
    image: "drivehub.azurecr.io/meateam/delegation-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "3012:8080"
    env_file:
      - /root/PROD/kd.config
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

  permit-service:
    image: "drivehub.azurecr.io/meateam/permit-service:v2.0.0"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "--addr=:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - /root/PROD/kd.config
    ports:
      - "3013:8080"
    depends_on:
      - spike-service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
          